
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using api.Models;
using Api.Models;

namespace api.DTOs
{
    public static class DataSeeder
    {
        public static void SeedData(MoodQuotesDbContext context)
        {
            if (context.Authors.Any()) return;

            var now = DateTime.UtcNow;

            var authors = new[]
            {
                new Author { Name = "Maya Angelou", Bio = "American poet, memoirist, and civil rights activist", CreatedAt = now },
                new Author { Name = "Viktor Frankl", Bio = "Austrian neurologist, psychiatrist, and Holocaust survivor", CreatedAt = now },
                new Author { Name = "Rumi", Bio = "13th-century Persian poet, Islamic scholar, and Sufi mystic", CreatedAt = now },
                new Author { Name = "Buddha", Bio = "Spiritual teacher and founder of Buddhism", CreatedAt = now },
                new Author { Name = "Marcus Aurelius", Bio = "Roman emperor and Stoic philosopher", CreatedAt = now },
                new Author { Name = "Anonymous", Bio = "Unknown author", CreatedAt = now },
                new Author { Name = "John Green", Bio = "American author", CreatedAt = now },
                new Author { Name = "Albert Camus", Bio = "French philosopher, author, and journalist", CreatedAt = now },
                new Author { Name = "Victor Hugo", Bio = "French poet, novelist, and dramatist", CreatedAt = now },
                new Author { Name = "Emily Dickinson", Bio = "American poet", CreatedAt = now },
                new Author { Name = "Ernest Hemingway", Bio = "American novelist, short-story writer, and journalist", CreatedAt = now },
                new Author { Name = "Nelson Mandela", Bio = "South African anti-apartheid revolutionary, political leader, and philanthropist", CreatedAt = now },
                new Author { Name = "A.A. Milne", Bio = "English author", CreatedAt = now },
                new Author { Name = "Winston Churchill", Bio = "British statesman, soldier, and writer", CreatedAt = now },
                new Author { Name = "Confucius", Bio = "Chinese philosopher and politician", CreatedAt = now },
                new Author { Name = "Brené Brown", Bio = "American research professor, lecturer, author, and podcast host", CreatedAt = now },
                new Author { Name = "Stephen Fry", Bio = "English actor, comedian, and writer", CreatedAt = now },
                new Author { Name = "Dan Millman", Bio = "American author and lecturer", CreatedAt = now },
                new Author { Name = "William James", Bio = "American philosopher and psychologist", CreatedAt = now },
                new Author { Name = "Walter Anderson", Bio = "American painter, writer, and naturalist", CreatedAt = now },
                new Author { Name = "Amit Ray", Bio = "Indian author and spiritual master", CreatedAt = now },
                new Author { Name = "Thich Nhat Hanh", Bio = "Vietnamese Thiền Buddhist monk, peace activist, and author", CreatedAt = now },
                new Author { Name = "Roy Bennett", Bio = "Author", CreatedAt = now },
                new Author { Name = "Lao Tzu", Bio = "Ancient Chinese philosopher and writer", CreatedAt = now },
                new Author { Name = "Martin Luther King Jr.", Bio = "American Baptist minister and activist", CreatedAt = now },
                new Author { Name = "Alexander Graham Bell", Bio = "Scottish-born inventor, scientist, and engineer", CreatedAt = now },
                new Author { Name = "Tim Ferriss", Bio = "American entrepreneur, investor, author, and podcaster", CreatedAt = now },
                new Author { Name = "Bruce Lee", Bio = "Hong Kong and American martial artist, actor, director, and philosopher", CreatedAt = now },
                new Author { Name = "Ralph Waldo Emerson", Bio = "American essayist, lecturer, philosopher, and poet", CreatedAt = now },
                new Author { Name = "R.M. Drake", Bio = "American author", CreatedAt = now },
                new Author { Name = "Jean de La Fontaine", Bio = "French fabulist and one of the most widely read French poets of the 17th century", CreatedAt = now },
                new Author { Name = "Christopher Morley", Bio = "American journalist, novelist, essayist, and poet", CreatedAt = now },
                new Author { Name = "Mary Anne Radmacher", Bio = "American writer and artist", CreatedAt = now },
                new Author { Name = "Jonathan Safran Foer", Bio = "American novelist", CreatedAt = now },
                new Author { Name = "Leonardo da Vinci", Bio = "Italian polymath of the High Renaissance", CreatedAt = now },
                new Author { Name = "Bob Marley", Bio = "Jamaican singer, songwriter, and musician", CreatedAt = now },
                new Author { Name = "Anne Lamott", Bio = "American novelist and non-fiction writer", CreatedAt = now },
                new Author { Name = "Seneca", Bio = "Roman Stoic philosopher, statesman, and dramatist", CreatedAt = now },
                new Author { Name = "Michel de Montaigne", Bio = "One of the most significant philosophers of the French Renaissance", CreatedAt = now },
                new Author { Name = "Mandy Hale", Bio = "American author", CreatedAt = now },
                new Author { Name = "Johann Wolfgang von Goethe", Bio = "German poet, playwright, novelist, scientist, statesman, theatre director, and critic", CreatedAt = now },
                new Author { Name = "Laurence Sterne", Bio = "Anglo-Irish novelist and Anglican cleric", CreatedAt = now },
                new Author { Name = "May Sarton", Bio = "American poet, novelist and memoirist", CreatedAt = now },
                new Author { Name = "Mother Teresa", Bio = "Albanian-Indian Roman Catholic nun and missionary", CreatedAt = now },
                new Author { Name = "Douglas Coupland", Bio = "Canadian novelist and artist", CreatedAt = now },
                new Author { Name = "Kim Culbertson", Bio = "American author", CreatedAt = now },
                new Author { Name = "Richard Bach", Bio = "American writer", CreatedAt = now },
                new Author { Name = "Anurag Prakash Ray", Bio = "Author", CreatedAt = now },
                new Author { Name = "Jean-Paul Sartre", Bio = "French philosopher, playwright, novelist, screenwriter, political activist, biographer, and literary critic", CreatedAt = now },
                new Author { Name = "Connor Chalfant", Bio = "Author", CreatedAt = now },
                new Author { Name = "Ellen Burstyn", Bio = "American actress", CreatedAt = now },
                new Author { Name = "Robert Green Ingersoll", Bio = "American writer and orator", CreatedAt = now },
                new Author { Name = "William Arthur Ward", Bio = "American author", CreatedAt = now },
                new Author { Name = "James Thurber", Bio = "American cartoonist, author, humorist, journalist, and playwright", CreatedAt = now },
                new Author { Name = "Mehmet Oz", Bio = "Turkish-American television personality, cardiothoracic surgeon, and author", CreatedAt = now },
                new Author { Name = "Eckhart Tolle", Bio = "Spiritual teacher and author", CreatedAt = now },
                new Author { Name = "Marshall Rosenberg", Bio = "American psychologist, mediator, author and teacher", CreatedAt = now },
                new Author { Name = "Eleanor Roosevelt", Bio = "American political figure, diplomat, and activist", CreatedAt = now },
                new Author { Name = "Henry Ford", Bio = "American industrialist and business magnate", CreatedAt = now },
                new Author { Name = "Dale Carnegie", Bio = "American writer and lecturer", CreatedAt = now },
                new Author { Name = "Les Brown", Bio = "American motivational speaker, author, and former politician", CreatedAt = now },
                new Author { Name = "George Eliot", Bio = "English novelist, poet, journalist, translator and one of the leading writers of the Victorian era", CreatedAt = now },
                new Author { Name = "Zig Ziglar", Bio = "American author, salesman, and motivational speaker", CreatedAt = now },
                new Author { Name = "Theodore Roosevelt", Bio = "American statesman, politician, conservationist, naturalist, and writer", CreatedAt = now },
                new Author { Name = "Morgan Harper Nichols", Bio = "American writer, artist, and musician", CreatedAt = now },
                new Author { Name = "Etty Hillesum", Bio = "Dutch Jewish writer", CreatedAt = now },
                new Author { Name = "Sharon Salzberg", Bio = "American author and teacher of Buddhist meditation traditions", CreatedAt = now },
                new Author { Name = "Max Lucado", Bio = "American author and pastor", CreatedAt = now },
                new Author { Name = "Kurt Cobain", Bio = "American singer, songwriter, and musician", CreatedAt = now },
                new Author { Name = "Harvey Fierstein", Bio = "American actor, playwright, and screenwriter", CreatedAt = now },
                new Author { Name = "Stephanie Bennett-Henry", Bio = "Author", CreatedAt = now },
                new Author { Name = "Vincent Van Gogh", Bio = "Dutch Post-Impressionist painter", CreatedAt = now },
                new Author { Name = "Louise Hay", Bio = "American motivational author", CreatedAt = now },
                new Author { Name = "Blake Lively", Bio = "American actress", CreatedAt = now },
                new Author { Name = "Marcus Tullius Cicero", Bio = "Roman statesman, lawyer, scholar, and philosopher", CreatedAt = now },
                new Author { Name = "Toni Morrison", Bio = "American novelist", CreatedAt = now },
                new Author { Name = "Oscar Wilde", Bio = "Irish poet and playwright", CreatedAt = now },
                new Author { Name = "Socrates", Bio = "Greek philosopher from Athens", CreatedAt = now },
                new Author { Name = "Steve Maraboli", Bio = "American author and speaker", CreatedAt = now },
                new Author { Name = "Mila Bron", Bio = "Author", CreatedAt = now },
                new Author { Name = "Brittany Burgunder", Bio = "American author and motivational speaker", CreatedAt = now },
                new Author { Name = "C. JoyBell C.", Bio = "Author", CreatedAt = now },
                new Author { Name = "Melanie Koulouris", Bio = "Author", CreatedAt = now },
                new Author { Name = "Jennifer Edwards", Bio = "Author", CreatedAt = now },
                new Author { Name = "Marianne Williamson", Bio = "American author, spiritual leader, and political activist", CreatedAt = now },
                new Author { Name = "Veronica Roth", Bio = "American novelist and short story writer", CreatedAt = now },
                new Author { Name = "Elder David A. Bednar", Bio = "American religious leader", CreatedAt = now },
                new Author { Name = "Maureen Johnson", Bio = "American author of young adult fiction", CreatedAt = now },
                new Author { Name = "Desmond Tutu", Bio = "South African Anglican cleric and theologian", CreatedAt = now },
                new Author { Name = "Jonas Salk", Bio = "American virologist and medical researcher", CreatedAt = now },
                new Author { Name = "Anne Frank", Bio = "German-Dutch diarist of Jewish heritage", CreatedAt = now },
                new Author { Name = "Samuel Smiles", Bio = "Scottish author and government reformer", CreatedAt = now },
                new Author { Name = "Rebecca Solnit", Bio = "American writer", CreatedAt = now },
                new Author { Name = "Aristotle", Bio = "Greek philosopher and polymath", CreatedAt = now },
                new Author { Name = "Robert H. Schuller", Bio = "American televangelist, pastor, and author", CreatedAt = now },
                new Author { Name = "Christopher Reeve", Bio = "American actor, director, and activist", CreatedAt = now },
                new Author { Name = "Bernard Williams", Bio = "English moral philosopher", CreatedAt = now },
                new Author { Name = "Suzanne Collins", Bio = "American author and television writer", CreatedAt = now },
                new Author { Name = "Howard Zinn", Bio = "American historian, playwright, and social activist", CreatedAt = now }
            };

            context.Authors.AddRange(authors);
            context.SaveChanges();

            var quotes = new[]
            {
                // Depression
                new Quote { Text = "The greater the difficulty, the more glory in surmounting it.", AuthorId = 6, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "There is hope, even when your brain tells you there isn’t.", AuthorId = 7, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "In the depths of winter, I finally learned that within me there lay an invincible summer.", AuthorId = 8, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "Even the darkest night will end, and the sun will rise.", AuthorId = 9, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "Hope is the thing with feathers that perches in the soul and sings the tune without the words and never stops at all.", AuthorId = 10, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "The world breaks everyone, and afterward many are strong at the broken places.", AuthorId = 11, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "The greatest glory in living lies not in never falling, but in rising every time we fall.", AuthorId = 12, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "You are stronger than you seem, braver than you believe, and smarter than you think.", AuthorId = 13, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "If you're going through hell, keep going.", AuthorId = 14, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "It does not matter how slowly you go as long as you do not stop.", AuthorId = 15, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "You, yourself, as much as anybody in the entire universe, deserve your love and affection.", AuthorId = 4, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "It’s okay not to be okay.", AuthorId = 6, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "Talk to yourself like you would to someone you love.", AuthorId = 16, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "Your mental health is just as important as your physical health.", AuthorId = 6, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "You are not your depression. You are a person who has depression.", AuthorId = 17, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "When we can no longer change a situation, we are challenged to change ourselves.", AuthorId = 2, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "The darkest moments are to be cherished, for they are the greatest teachers.", AuthorId = 3, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened, ambition inspired, and success achieved.", AuthorId = 6, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "I have not failed. I've just found 10,000 ways that won't work.", AuthorId = 6, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },
                new Quote { Text = "It is during our darkest moments that we must focus to see the light.", AuthorId = 6, MoodType = MoodType.Depression, IsActive = true, CreatedAt = now },

                // Anxiety
                new Quote { Text = "You don’t have to control your thoughts. You just have to stop letting them control you.", AuthorId = 18, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "The greatest weapon against stress is our ability to choose one thought over another.", AuthorId = 19, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "Nothing diminishes anxiety faster than action.", AuthorId = 20, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "If you want to conquer the anxiety of life, live in the moment, live in the breath.", AuthorId = 21, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.", AuthorId = 22, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "You may not control all the events that happen to you, but you can decide not to be reduced by them.", AuthorId = 1, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "Instead of worrying about what you cannot control, shift your energy to what you can create.", AuthorId = 23, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "Our anxiety does not come from thinking about the future, but from wanting to control it.", AuthorId = 6, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "Difficult roads often lead to beautiful destinations. The best is yet to come.", AuthorId = 6, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "When I let go of what I am, I become what I might be.", AuthorId = 24, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "Just when the caterpillar thought the world was ending, he turned into a butterfly.", AuthorId = 6, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "Courage is not the absence of fear, but doing something in spite of fear.", AuthorId = 6, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "You're braver than you believe, and stronger than you seem, and smarter than you think.", AuthorId = 13, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "If you can’t fly then run, if you can’t run then walk, if you can’t walk then crawl, but whatever you do you have to keep moving forward.", AuthorId = 25, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "Peace comes from within. Do not seek it without.", AuthorId = 4, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "Anxiety is a thin stream of fear trickling through the mind. If encouraged, it cuts a channel into which all other thoughts are drained.", AuthorId = 6, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "Anxiety's like a rocking chair. It gives you something to do, but it doesn't get you very far.", AuthorId = 6, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "The largest part of what we call 'personality' is determined by how we've opted to defend ourselves against anxiety and sadness.", AuthorId = 6, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "Worrying is carrying tomorrow's load with today's strength- carrying two days at once. It is moving into tomorrow ahead of time. Worrying doesn't empty tomorrow of its sorrow, it empties today of its strength.", AuthorId = 6, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },
                new Quote { Text = "Rule number one is, don't sweat the small stuff. Rule number two is, it's all small stuff.", AuthorId = 6, MoodType = MoodType.Anxiety, IsActive = true, CreatedAt = now },

                // LackOfFocus
                new Quote { Text = "Concentrate all your thoughts upon the work in hand. The sun’s rays do not burn until brought to a focus.", AuthorId = 26, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "Focus on being productive instead of busy.", AuthorId = 27, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "Don’t dwell on what went wrong. Instead, focus on what to do next. Spend your energies on moving forward toward finding the answer.", AuthorId = 6, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "The key to success is to focus our conscious mind on things we desire not things we fear.", AuthorId = 6, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "Your destiny is to fulfill those things upon which you focus most intently. So choose to keep your focus on that which is truly magnificent, beautiful, uplifting and joyful.", AuthorId = 6, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "Lack of direction, not lack of time, is the problem. We all have twenty-four hour days.", AuthorId = 6, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "Successful people maintain a positive focus in life no matter what is going on around them.", AuthorId = 6, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "The successful warrior is the average man, with laser-like focus.", AuthorId = 28, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "Concentration is the secret of strength in politics, in war, in trade, in short, in all management of human affairs.", AuthorId = 29, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "To create something exceptional, your mindset must be relentlessly focused on the smallest detail.", AuthorId = 6, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "Focus on the step in front of you, not the whole staircase.", AuthorId = 5, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "The main thing is to keep the main thing the main thing.", AuthorId = 6, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "What you focus on expands.", AuthorId = 6, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "It is those who concentrate on but one thing at a time who advance in this world.", AuthorId = 6, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "My success, part of it certainly, is that I have focused in on a few things.", AuthorId = 6, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "The power of concentration is the only key to the treasure-house of knowledge.", AuthorId = 6, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "To be everywhere is to be nowhere.", AuthorId = 6, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "The shorter way to do many things is to do only one thing at a time.", AuthorId = 6, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "One reason so few of us achieve what we truly want is that we never direct our focus; we never concentrate our power.", AuthorId = 6, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },
                new Quote { Text = "You will never reach your destination if you stop and throw stones at every dog that barks.", AuthorId = 14, MoodType = MoodType.LackOfFocus, IsActive = true, CreatedAt = now },

                // Sadness
                new Quote { Text = "The darkest hour is just before the dawn.", AuthorId = 6, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "We must understand that sadness is an ocean, and sometimes we drown, while other days we are forced to swim.", AuthorId = 30, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Sadness flies away on the wings of time.", AuthorId = 31, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Heavy hearts, like heavy clouds in the sky, are best relieved by the letting of a little water.", AuthorId = 32, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Courage doesn’t always roar. Sometimes courage is the quiet voice at the end of the day saying, ‘I will try again tomorrow.’", AuthorId = 33, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "You cannot protect yourself from sadness without protecting yourself from happiness.", AuthorId = 34, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Tears come from the heart and not from the brain.", AuthorId = 35, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "The good times of today are the sad thoughts of tomorrow.", AuthorId = 36, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Perhaps the butterfly is proof that you can go through a great deal of darkness yet become something beautiful again.", AuthorId = 6, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "The word 'happy' would lose its meaning if it were not balanced by sadness.", AuthorId = 6, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Sadness is but a wall between two gardens.", AuthorId = 6, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "There are moments when I wish I could roll back the clock and take all the sadness away, but I have the feeling that if I did, the joy would be gone as well.", AuthorId = 6, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "The walls we build around us to keep sadness out also keeps out the joy.", AuthorId = 6, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "It's sad when someone you know becomes someone you knew.", AuthorId = 6, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Every human walks around with a certain kind of sadness. They may not wear it on their sleeves, but it’s there if you look deep.", AuthorId = 6, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "The way sadness works is one of the strange riddles of the world.", AuthorId = 6, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "There is no greater sorrow than to recall in misery the time when we were happy.", AuthorId = 6, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "The soul would have no rainbow had the eyes no tears.", AuthorId = 6, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Don't cry because it's over, smile because it happened.", AuthorId = 6, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },
                new Quote { Text = "The only way to get over a death is by seeing it as a life completed, instead of a life interrupted.", AuthorId = 6, MoodType = MoodType.Sadness, IsActive = true, CreatedAt = now },

                // Stress
                new Quote { Text = "The greatest weapon against stress is our ability to choose one thought over another.", AuthorId = 19, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "It’s not stress that kills us, it is our reaction to it.", AuthorId = 6, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "Breathe. Let go. And remind yourself that this very moment is the only one you know you have for sure.", AuthorId = 6, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "The time to relax is when you don’t have time for it.", AuthorId = 6, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "You cannot always control what goes on outside, but you can always control what goes on inside.", AuthorId = 6, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.", AuthorId = 22, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "Don’t believe every worried thought you have. Worried thoughts are notoriously inaccurate.", AuthorId = 6, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "The man who moves a mountain begins by carrying away small stones.", AuthorId = 15, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "Peace is the result of retraining your mind to process life as it is, rather than as you think it should be.", AuthorId = 6, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "Within you, there is a stillness and a sanctuary to which you can retreat at any time and be yourself.", AuthorId = 6, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "Almost everything will work again if you unplug it for a few minutes, including you.", AuthorId = 37, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "We suffer more often in imagination than in reality.", AuthorId = 38, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "You have power over your mind - not outside events. Realize this, and you will find strength.", AuthorId = 5, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "Stress is caused by being ‘here’ but wanting to be ‘there.’", AuthorId = 6, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "The day she let go of the things that were weighing her down, was the day she began to shine the brightest.", AuthorId = 6, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "Stress is the trash of modern life-we all generate it, but if you don't dispose of it properly, it will pile up and overtake your life.", AuthorId = 6, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "One of the best ways to reduce stress is to accept the things you cannot control.", AuthorId = 6, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "The mind can go in a thousand directions, but on this beautiful path, I walk in peace. With each step, the wind blows. With each step, a flower blooms.", AuthorId = 22, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "Don't stress the could haves, if it should have, it would have.", AuthorId = 6, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },
                new Quote { Text = "You can't calm the storm, so stop trying. What you can do is calm yourself. The storm will pass.", AuthorId = 6, MoodType = MoodType.Stress, IsActive = true, CreatedAt = now },

                // Loneliness
                new Quote { Text = "The greatest thing in the world is to know how to belong to oneself.", AuthorId = 39, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "I restore myself when I’m alone.", AuthorId = 6, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "A season of loneliness and isolation is when the caterpillar gets its wings. Remember that next time you feel alone.", AuthorId = 40, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Sometimes you have to stand alone just to make sure you still can.", AuthorId = 6, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "The soul that sees beauty may sometimes walk alone.", AuthorId = 41, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "In solitude, the mind gains strength and learns to lean upon itself.", AuthorId = 42, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Loneliness is the poverty of self; solitude is the richness of self.", AuthorId = 43, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "The most terrible poverty is loneliness, and the feeling of being unloved.", AuthorId = 44, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Remember: the time you feel lonely is the time you most need to be by yourself. Life’s cruelest irony.", AuthorId = 45, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "People think being alone makes you lonely, but I don’t think that’s true. Being surrounded by the wrong people is the loneliest thing in the world.", AuthorId = 46, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "You are never alone; you are eternally connected with everyone.", AuthorId = 47, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "There is hope, even when your brain tells you there isn’t.", AuthorId = 7, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "I define connection as the energy that exists between people when they feel seen, heard, and valued; when they can give and receive without judgment; and when they derive sustenance and strength from the relationship.", AuthorId = 16, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Don’t feel alone, because there is always someone out there who loves you more than you can imagine.", AuthorId = 48, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "If you are lonely when you're alone, you are in bad company.", AuthorId = 49, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Find company within yourself and you’ll never spend a day alone. Find love within yourself and you’ll never have a lonely day.", AuthorId = 50, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "What a lovely surprise to discover how un-lonely being alone can be.", AuthorId = 51, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "You yourself, as much as anybody in the entire universe, deserve your love and affection.", AuthorId = 4, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Loneliness adds beauty to life. It puts a special burn on sunsets and makes night air smell better.", AuthorId = 6, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },
                new Quote { Text = "The eternal quest of the individual human being is to shatter his loneliness.", AuthorId = 6, MoodType = MoodType.Loneliness, IsActive = true, CreatedAt = now },

                // Anger
                new Quote { Text = "For every minute you remain angry, you give up sixty seconds of peace of mind.", AuthorId = 29, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "Holding on to anger is like grasping a hot coal with the intent of throwing it at someone else; you are the one who gets burned.", AuthorId = 4, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "Anger is an acid that can do more harm to the vessel in which it is stored than to anything on which it is poured.", AuthorId = 6, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "When anger rises, think of the consequences.", AuthorId = 15, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "It is wise to direct your anger towards problems, not people—to focus your energies on answers, not excuses.", AuthorId = 53, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "You will not be punished for your anger; you will be punished by your anger.", AuthorId = 4, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "Anger is a wind which blows out the lamp of the mind.", AuthorId = 52, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "The greatest remedy for anger is delay.", AuthorId = 6, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "When angry count to ten before you speak. If very angry, count to one hundred.", AuthorId = 6, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "Anybody can become angry—that is easy, but to be angry with the right person and to the right degree and at the right time and for the right purpose, and in the right way—that is not within everybody’s power and is not easy.", AuthorId = 96, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "Let us not look back in anger, nor forward in fear, but around in awareness.", AuthorId = 54, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "The opposite of anger is not calmness, its empathy.", AuthorId = 55, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "How much more grievous are the consequences of anger than the causes of it.", AuthorId = 5, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "Where there is anger, there is always pain underneath.", AuthorId = 56, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "At the core of all anger is a need that is not being fulfilled.", AuthorId = 57, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "Never respond to an angry person with a fiery comeback, even if he deserves it...Don't allow his anger to become your anger.", AuthorId = 6, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "Anger, resentment and jealousy doesn't change the heart of others-- it only changes yours.", AuthorId = 6, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "Speak when you are angry and you will make the best speech you will ever regret.", AuthorId = 6, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "A moment of patience in a moment of anger saves you a hundred moments of regret.", AuthorId = 6, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },
                new Quote { Text = "Bitterness is like cancer. It eats upon the host. But anger is like fire. It burns it all clean.", AuthorId = 6, MoodType = MoodType.Anger, IsActive = true, CreatedAt = now },

                // Fear
                new Quote { Text = "You gain strength, courage and confidence by every experience in which you really stop to look fear in the face.", AuthorId = 58, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "The brave man is not he who does not feel afraid, but he who conquers that fear.", AuthorId = 12, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "Inaction breeds doubt and fear. Action breeds confidence and courage. If you want to conquer fear, do not sit home and think about it. Go out and get busy.", AuthorId = 60, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "I learned that courage was not the absence of fear, but the triumph over it.", AuthorId = 12, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "Courage is resistance to fear, mastery of fear - not absence of fear.", AuthorId = 6, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "One of the greatest discoveries a man makes, one of his great surprises, is to find he can do what he was afraid he couldn’t do.", AuthorId = 62, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "Do one thing every day that scares you.", AuthorId = 58, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "Too many of us are not living our dreams because we are living our fears.", AuthorId = 61, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "Everything you’ve ever wanted is on the other side of fear.", AuthorId = 63, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "He who is not everyday conquering some fear has not learned the secret of life.", AuthorId = 29, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "Avoiding danger is no safer in the long run than outright exposure. The fearful are caught as often as the bold.", AuthorId = 6, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "The only thing we have to fear is fear itself.", AuthorId = 64, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "Fears are nothing more than a state of mind.", AuthorId = 6, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "Thinking will not overcome fear but action will.", AuthorId = 6, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "Do what you fear and fear disappears.", AuthorId = 6, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "Fear is only as deep as the mind allows.", AuthorId = 6, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "Of all the liars in the world, sometimes the worst are our own fears.", AuthorId = 6, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "Fear is a darkroom where negatives develop.", AuthorId = 6, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "Fear is the path to the dark side. Fear leads to anger. Anger leads to hate. Hate leads to suffering.", AuthorId = 6, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },
                new Quote { Text = "The key to change... is to let go of fear.", AuthorId = 6, MoodType = MoodType.Fear, IsActive = true, CreatedAt = now },

                // Overwhelmed
                new Quote { Text = "You don’t have to see the whole staircase, just take the first step.", AuthorId = 25, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "It’s not the load that breaks you, it’s the way you carry it.", AuthorId = 6, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "Anxiety happens when you think you have to figure everything out all at once. Breathe. You’re strong. You got this. Take it day by day.", AuthorId = 6, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "Do what you can, with what you have, where you are.", AuthorId = 64, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "The greatest weapon against stress is our ability to choose one thought over another.", AuthorId = 19, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "Sometimes the most important thing in a whole day is the rest we take between two deep breaths.", AuthorId = 66, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "If you’re going through hell, keep going.", AuthorId = 14, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "You are worth the quiet moment. You are worth the deeper breaths, and you are worth the time it takes to slow down, be still, and rest.", AuthorId = 65, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "This too shall pass.", AuthorId = 6, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", AuthorId = 3, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "The feeling of being overwhelmed is often a sign that you're growing.", AuthorId = 6, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "Overwhelmed is just a feeling. It’s not a state of being.", AuthorId = 6, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "When you feel overwhelmed, remember that you're not alone. Many people feel the same way.", AuthorId = 6, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "It's okay to feel overwhelmed. It's not okay to stay there.", AuthorId = 6, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "The next time you feel overwhelmed, just take a deep breath and remind yourself that you're in control.", AuthorId = 6, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "Don't be afraid to ask for help when you're feeling overwhelmed. It's a sign of strength, not weakness.", AuthorId = 6, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "When you're feeling overwhelmed, focus on one thing at a time. You'll be surprised at how much you can accomplish.", AuthorId = 6, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "The best way to deal with feeling overwhelmed is to take a break. Step away from the situation and come back with a fresh perspective.", AuthorId = 6, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "If you're feeling overwhelmed, remember that you're not a machine. You need to take care of yourself, both physically and mentally.", AuthorId = 6, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },
                new Quote { Text = "The most important thing to remember when you're feeling overwhelmed is that you're not alone. There are people who care about you and want to help.", AuthorId = 6, MoodType = MoodType.Overwhelmed, IsActive = true, CreatedAt = now },

                // LowSelfEsteem
                new Quote { Text = "You yourself, as much as anybody in the entire universe, deserve your love and affection.", AuthorId = 67, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "You are valuable simply because you exist. Not because of what you do or what you have done, but simply because you are.", AuthorId = 68, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "You alone are enough. You have nothing to prove to anybody.", AuthorId = 1, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "Wanting to be someone else is a waste of the person you are.", AuthorId = 69, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "Never be bullied into silence. Never allow yourself to be made a victim. Accept no one’s definition of your life, but define yourself.", AuthorId = 70, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "Always remember you are braver than you believe, stronger than you seem, and smarter than you think.", AuthorId = 13, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "Life is tough, my darling, but so are you.", AuthorId = 71, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "If you hear a voice within you say ‘you cannot paint,’ then by all means paint, and that voice will be silenced.", AuthorId = 72, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "Remember, you have been criticizing yourself for years, and it hasn’t worked. Try approving of yourself and see what happens.", AuthorId = 73, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "Believe you can and you’re halfway there.", AuthorId = 64, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "The most beautiful thing you can wear is confidence.", AuthorId = 74, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "If you have no confidence in self, you are twice defeated in the race of life. With confidence, you have won even before you have started.", AuthorId = 75, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", AuthorId = 29, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "You are enough, a thousand times enough.", AuthorId = 6, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "You are your best thing.", AuthorId = 76, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "To love oneself is the beginning of a lifelong romance.", AuthorId = 77, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "Know thyself.", AuthorId = 78, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "You are braver than you believe, stronger than you seem, and smarter than you think.", AuthorId = 1, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "The strongest principle of growth lies in human choice.", AuthorId = 62, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },
                new Quote { Text = "The only person who can pull me down is myself, and I'm not going to let myself pull me down anymore.", AuthorId = 6, MoodType = MoodType.LowSelfEsteem, IsActive = true, CreatedAt = now },

                // Guilt
                new Quote { Text = "The truth is, unless you let go, unless you forgive yourself, unless you forgive the situation, unless you realize that the situation is over, you cannot move forward.", AuthorId = 79, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "To heal, we must first forgive… and sometimes the person we must forgive is ourselves.", AuthorId = 80, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "Forgiving yourself, believing in yourself, and choosing to love yourself are the best gifts one could receive.", AuthorId = 81, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "I have learned that the person I have to ask for forgiveness from the most is: myself. You must love yourself. You have to forgive yourself, everyday, whenever you remember a shortcoming, a flaw, you have to tell yourself. ‘That’s just fine’. You have to forgive yourself so much, until you don’t even see those things anymore. Because that’s what love is like.", AuthorId = 82, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "Forgive yourself for not knowing what you didn’t know before you learned it.", AuthorId = 1, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "There is no sense in punishing your future for the mistakes of your past. Forgive yourself, grow from it, and then let it go.", AuthorId = 83, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "Your past mistakes are meant to guide you, not define you.", AuthorId = 6, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "The beauty of life is, while we cannot undo what is done, we can see it, understand it, learn from it and change so that every new moment is spent not in regret, guilt, fear, or anger but wisdom, understanding, and love.", AuthorId = 84, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "We do not heal the past by dwelling there; we heal the past by living fully in the present.", AuthorId = 85, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "Maybe there’s more we all could have done, but we just have to let the guilt remind us to do better next time.", AuthorId = 86, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "Let your guilt be your fuel. Let it remind you of who you want to be. Draw a line in your mind. Never cross it again.", AuthorId = 6, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "Guilt is not a response to anger; it is a response to one’s own actions or lack of action. If it leads to change, it can be useful.", AuthorId = 6, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "Guilt is to the spirit what pain is to the body.", AuthorId = 87, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "Guilt is a useless feeling. It’s never enough to make you change direction--only enough to make you useless.", AuthorId = 6, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "Guilt isn’t always a rational thing… Guilt is a weight that will crush you whether you deserve it or not.", AuthorId = 88, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "Guilt is the price we pay willingly for doing what we are going to do anyway.", AuthorId = 6, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "There is a luxury in self-reproach. When we blame ourselves, we feel that no one else has a right to blame us.", AuthorId = 6, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "Guilt is perhaps the most painful companion of death.", AuthorId = 6, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "The best way to assuage your guilt is to do something good for someone else.", AuthorId = 6, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },
                new Quote { Text = "Guilt is a destructive and ultimately pointless emotion.", AuthorId = 6, MoodType = MoodType.Guilt, IsActive = true, CreatedAt = now },

                // Hopelessness
                new Quote { Text = "Hope is being able to see that there is light despite all of the darkness.", AuthorId = 89, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "We must accept finite disappointment, but never lose infinite hope.", AuthorId = 25, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Hope is the thing with feathers that perches in the soul and sings the tune without the words and never stops at all.", AuthorId = 10, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Hope lies in dreams, in imagination, and in the courage of those who dare to make dreams into reality.", AuthorId = 90, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "I don’t think of all the misery, but of the beauty that still remains.", AuthorId = 91, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Hope is like the sun, which, as we journey toward it, casts the shadow of our burden behind us.", AuthorId = 92, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "When you’re at the end of your rope, tie a knot and hold on.", AuthorId = 64, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "The future is dark, with a darkness as much of the womb as the grave.", AuthorId = 93, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Hope is a waking dream.", AuthorId = 96, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Let your hopes, not your hurts, shape your future.", AuthorId = 94, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Once you choose hope, anything’s possible.", AuthorId = 95, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "There was never a night or a problem that could defeat sunrise or hope.", AuthorId = 97, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Hope is the only thing stronger than fear.", AuthorId = 98, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "To be hopeful in bad times is not just foolishly romantic. It is based on the fact that human history is a history not only of cruelty, but also of compassion, sacrifice, courage, kindness.", AuthorId = 99, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "The very least you can do in your life is figure out what you hope for. And the most you can do is live inside that hope. Not admire it from a distance but live right in it, under its roof.", AuthorId = 6, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Hope is a verb with its shirtsleeves rolled up.", AuthorId = 6, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Hope is not an emotion; it's a way of thinking or a cognitive process.", AuthorId = 6, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "Hope is important because it can make the present moment less difficult to bear. If we believe that tomorrow will be better, we can bear a hardship today.", AuthorId = 6, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "A leader is a dealer in hope.", AuthorId = 6, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now },
                new Quote { Text = "All human wisdom is summed up in two words; wait and hope.", AuthorId = 6, MoodType = MoodType.Hopelessness, IsActive = true, CreatedAt = now }
            };

            context.Quotes.AddRange(quotes);
            context.SaveChanges();
        }
    }
}
